name = "NeoForge Modpack"
author = "deusdormit"
version = "1.0.0"
description = "Client and server NeoForge modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e2ab531b30abc905cdb11f750217ae14c6c5d70cf4c87e93423d489ac234b6e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
