name = "NeoForge Modpack"
author = "deusdormit"
version = "1.0.0"
description = "Client and server NeoForge modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d9ebe5dc29d5f1b69ab6687ed5d34a9bb119241103df519386aba4c2e1e011"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
