name = "NeoForge Modpack"
author = "deusdormit"
version = "1.0.0"
description = "Client and server NeoForge modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da238f97badd2afc15567cf632d795b87c33ee374ea0a6e854b5773bc6df3763"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
